### ISSUE TITLE
[FEATURE] 사용자 인증 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#1]
### Description
사용자 인증 화면을 구현합니다.

### ToDo
- [x] 사용자 로그인 화면 구현
- [x] 사용자 정보 입력 화면 구현
- [x] 인증 관련 매니저 타입 구현
- [x] 네트워크 타입 구현

### ETC
- 애플 로그인 설정 찾아보고 설정하기
