### ISSUE TITLE
[FEATURE] 챌린지 상태 관련 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#12]
### Description
챌린지 상태 관련 화면 구현

### ToDo
- [x] 챌린지 상태 화면 구현
- [x] 챌린지 누적 금액 화면
- [x] 인증 리스트 화면
- [ ] 인증 세부 사항 화면

### ETC
기타사항, 추가사항에 대해서 작성하세요.
