### ISSUE TITLE
[FEATURE] 마이 페이지 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#16]
### Description
마이페이지 화면 객체만 구성합니다.

### ToDo
- [ ] 마이페이지 헤더 구현
- [ ] 마이페이지 사용자 정보 구현
- [ ] 챌린지 상태 섹션 구현
- [ ] 승리 뱃지 상태 구현

### ETC
기타사항, 추가사항에 대해서 작성하세요.
