### ISSUE TITLE
[FEATURE] 홈화면 참여중인 챌린지 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#18]
### Description
홈화면 사용자 참여중인 챌린지 화면 구현

### ToDo
- [ ] 사용자 챌린지 참여 여부에 따른 화면 구현
- [ ] 사용자 챌린지 상태 네트워크 불러오기 구현
- [ ] 사용자 챌린지 상태에 따른 화면 전환 구현하기

### ETC
기타사항, 추가사항에 대해서 작성하세요.
