### ISSUE TITLE
[FEATURE] 사용자 없는 챌린지 리스트 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#20]
### Description
홈 화면 내 사용자 없는 챌린지 화면을 구현

### ToDo
- [ ] 참가 사용자 없는 챌린지 화면 구현
- [ ] 참가 가능 챌린지 세부 화면 구현
- [ ] 참가 가능 챌린지 네트워크 구현

### ETC
기타사항, 추가사항에 대해서 작성하세요.
