### ISSUE TITLE
[FEATURE] 챌린지 둘러보기 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#27]
### Description
챌린지 둘러보기 화면 구현

### ToDo
- [ ] 챌린지 리스트 화면 구현
- [ ] 챌린지 둘러보기 화면 필터링 구현
- [ ] 챌린지 방 생성 화면으로 이동 구현
- [ ] 챌린지 참가 화면 구현

### ETC
기타사항, 추가사항에 대해서 작성하세요.
