### ISSUE TITLE
[FEATURE] 참여 챌린지 상세 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#39]
### Description
챌린지 참여 상세 화면 구현

### ToDo
- [x] 챌린지 참여 화면 구현
- [x] 챌린지 인증 글 작성 화면 구현
- [x] 챌린지 인증 글 상세 화면 구현

### ETC
기타사항, 추가사항에 대해서 작성하세요.
