### ISSUE TITLE
[FEATURE] 생성된 챌린지 탐색 화면 구현

### ISSUE THREAD

**Issue by leegyoungmin** [potenday-project/IgoMoney_iOS#8]
### Description
챌린지 탐색 화면 구현

### ToDo
- [x] 빈 방 탐색 화면 구현
- [x] 방 입장 안내 화면 구현
- [ ] 생성된 챌린지 필터링
- [ ] 생성된 챌린지 모두 보기

### ETC
기타사항, 추가사항에 대해서 작성하세요.
